from typing import Dict, List, Optional
from langchain_core.messages import HumanMessage, SystemMessage
from datetime import datetime
from app.llm import get_llm

llm = get_llm(temperature=0)


def generate_comprehensive_notes(
    session_topic: str,
    checkpoints: List[Dict],
    weak_areas: List[str] = None,
    session_id: Optional[int] = None,
) -> str:
    # Agentic RAG: retrieve topic knowledge before generating notes
    rag_context = ""
    try:
        from app.services.rag_service import build_rag_context, ensure_session_knowledge
        if session_id:
            all_objectives = []
            all_concepts   = []
            for cp in checkpoints:
                all_objectives.extend(cp.get("objectives", []))
                all_concepts.extend(cp.get("key_concepts", []))
            ensure_session_knowledge(session_id, session_topic, all_objectives, all_concepts, checkpoints)
            rag_context = build_rag_context(
                base_context="",
                query=f"comprehensive notes for {session_topic}",
                session_id=session_id,
                topic=session_topic,
                objectives=all_objectives[:6],
                key_concepts=all_concepts[:8],
                max_extra_chars=2000,
            )
            print(f"notes_generator: Agentic RAG applied for session {session_id}")
    except Exception as e:
        print(f"notes_generator RAG error (non-fatal): {e}")

    system_msg = SystemMessage(content="""You are an expert study notes creator.
Create comprehensive, well-structured study notes with:
- Clear section organization
- Key concepts highlighted
- Memory aids and mnemonics
- Review questions
- Practical applications
Use markdown formatting.""")

    checkpoints_text = "\n".join([
        f"{i+1}. {cp.get('topic')} (Level: {cp.get('level', 'intermediate')})"
        for i, cp in enumerate(checkpoints)
    ])
    weak_areas_text = "\n".join(f"- {area}" for area in (weak_areas or []))
    rag_section = f"\n\nADDITIONAL KNOWLEDGE CONTEXT:\n{rag_context}" if rag_context.strip() else ""

    human_msg = HumanMessage(content=f"""Create comprehensive study notes for:

MAIN TOPIC: {session_topic}

COVERED CHECKPOINTS:
{checkpoints_text}

WEAK AREAS:
{weak_areas_text if weak_areas else "None identified"}
{rag_section}

Create detailed notes with:
1. Table of contents
2. Summary of each checkpoint
3. Key concepts and definitions
4. Memory aids and mnemonics
5. Practice questions
6. Study tips
7. Next steps

Format: Markdown with clear headers.""")

    response = llm.invoke([system_msg, human_msg])

    notes = f"""# Complete Learning Notes: {session_topic}

**Generated:** {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
**Total Checkpoints:** {len(checkpoints)}

---

{response.content}

---

## Study Tips for Mastery

1. **Spaced Repetition**: Review at intervals — Day 1, Day 3, Week 1, Week 2, Month 1
2. **Active Recall**: Test yourself without looking at notes
3. **Feynman Technique**: Explain in simple words, identify gaps, simplify further
4. **Practice Application**: Work on real projects and solve related problems
5. **Community Engagement**: Join forums and share your knowledge

## Action Items

- [ ] Review all checkpoints systematically
- [ ] Complete all practice questions
- [ ] Build a project using {session_topic}
- [ ] Teach these concepts to someone
- [ ] Explore advanced topics

---

*Generated by Conceptly - Your AI Learning Companion*
"""
    return notes


def generate_cheat_sheet(
    session_topic: str,
    checkpoints: List[Dict],
    session_id: Optional[int] = None,
) -> str:
    rag_context = ""
    try:
        from app.services.rag_service import build_rag_context, ensure_session_knowledge
        if session_id:
            all_objectives = []
            all_concepts   = []
            for cp in checkpoints:
                all_objectives.extend(cp.get("objectives", []))
                all_concepts.extend(cp.get("key_concepts", []))
            ensure_session_knowledge(session_id, session_topic, all_objectives, all_concepts, checkpoints)
            rag_context = build_rag_context(
                base_context="",
                query=f"cheat sheet key concepts {session_topic}",
                session_id=session_id,
                topic=session_topic,
                objectives=all_objectives[:4],
                key_concepts=all_concepts[:6],
                max_extra_chars=1000,
            )
    except Exception as e:
        print(f"notes_generator cheat sheet RAG error (non-fatal): {e}")

    system_msg = SystemMessage(content="""Create a concise cheat sheet.
Include key concepts only, quick reference format, bullet points.
Keep it under 500 words.""")

    checkpoints_text = "\n".join([
        f"- {cp.get('topic')}: {', '.join(cp.get('key_concepts', [])[:3])}"
        for cp in checkpoints
    ])
    rag_section = f"\n\nKEY KNOWLEDGE:\n{rag_context}" if rag_context.strip() else ""

    human_msg = HumanMessage(content=f"""Create quick reference cheat sheet for:

TOPIC: {session_topic}

CHECKPOINTS:
{checkpoints_text}
{rag_section}

Format: Markdown with clear sections and bullet points.""")

    response = llm.invoke([system_msg, human_msg])

    return f"""# {session_topic} - Quick Reference

**Generated:** {datetime.now().strftime("%B %d, %Y")}

---

{response.content}

---

*Quick reference only - Review full notes for details*
"""


def generate_practice_questions(
    session_topic: str,
    checkpoints: List[Dict],
    session_id: Optional[int] = None,
) -> str:
    rag_context = ""
    try:
        from app.services.rag_service import build_rag_context, ensure_session_knowledge
        if session_id:
            all_objectives = []
            all_concepts   = []
            for cp in checkpoints:
                all_objectives.extend(cp.get("objectives", []))
                all_concepts.extend(cp.get("key_concepts", []))
            ensure_session_knowledge(session_id, session_topic, all_objectives, all_concepts, checkpoints)
            rag_context = build_rag_context(
                base_context="",
                query=f"practice questions {session_topic}",
                session_id=session_id,
                topic=session_topic,
                objectives=all_objectives[:4],
                key_concepts=all_concepts[:6],
                max_extra_chars=1000,
            )
    except Exception as e:
        print(f"notes_generator practice q RAG error (non-fatal): {e}")

    system_msg = SystemMessage(content="""Generate practice questions for review.
Create multiple types (MCQ, short answer, conceptual) across difficulty levels.
Include answer key hints. Format with clear question numbering.""")

    checkpoints_text = "\n".join([
        f"{i+1}. {cp.get('topic')}: {', '.join(cp.get('objectives', [])[:2])}"
        for i, cp in enumerate(checkpoints)
    ])
    rag_section = f"\n\nKEY KNOWLEDGE:\n{rag_context}" if rag_context.strip() else ""

    human_msg = HumanMessage(content=f"""Generate practice questions for:

TOPIC: {session_topic}

CHECKPOINTS:
{checkpoints_text}
{rag_section}

Create at least 2-3 questions per checkpoint covering key concepts.""")

    response = llm.invoke([system_msg, human_msg])

    return f"""# {session_topic} - Practice Questions

**Generated:** {datetime.now().strftime("%B %d, %Y")}

---

{response.content}

---

## How to Use These Questions

1. **Initial Test**: Try answering without notes
2. **Review**: Check answers against materials
3. **Identify Gaps**: Note areas needing more study
4. **Repeat**: Retest yourself after studying

---

*Practice makes perfect!*
"""